apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: test
  name: node-dep
spec:
  replicas: 3
  selector:  
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:  
      containers:
        - name: node-app-container
          image: abismohammad/node-metrics-app:${IMAGE_TAG}
          ports:
           - containerPort: 3000 
