name: Deploy to Minikube (Local)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Show files
      run: ls -al

    - name: Set image tag
      run: echo "IMAGE_TAG=latest-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t abismohammad/node-metrics-app:${{ env.IMAGE_TAG }} .

    - name: Load Image into Minikube
      run: |
        minikube image load abismohammad/node-metrics-app:${{ env.IMAGE_TAG }}

    - name: Substitute Image Tag and Deploy
      run: |
        envsubst < deployment.yml | kubectl apply -f -
        kubectl apply -f service.yml

